## Exercice 1

In [1]:
import numpy as np

A = np.array([[1,0,-1],
              [1,2,1 ],
              [2,2,3 ]])

P = np.array([[1 , 2, 1],
              [-1,-1,-1],
              [0,-2,-2]])

### Partie A

__1)__

In [2]:
print("A^2=\n",A @ A)
print("\nA^3=\n",A @ A @ A)

A^2=
 [[-1 -2 -4]
 [ 5  6  4]
 [10 10  9]]

A^3=
 [[-11 -12 -13]
 [ 19  20  13]
 [ 38  38  27]]


__3)__

In [3]:
invA = (A @ A - 6*A + 11 * np.eye(3))/6
print('A^-1=\n',invA)

print('\nPour la passer en fractions:\n6A^-1=\n',invA*6)

A^-1=
 [[ 0.66666667 -0.33333333  0.33333333]
 [-0.16666667  0.83333333 -0.33333333]
 [-0.33333333 -0.33333333  0.33333333]]

Pour la passer en fractions:
6A^-1=
 [[ 4. -2.  2.]
 [-1.  5. -2.]
 [-2. -2.  2.]]


In [4]:
print("Vérification : calcul de l'inverse de A avec numpy :")

6* np.linalg.inv(A)

Vérification : calcul de l'inverse de A avec numpy :


array([[ 4., -2.,  2.],
       [-1.,  5., -2.],
       [-2., -2.,  2.]])

__4)__ Il faut résoudre $AX=b$

In [5]:
b = np.array([2,8,13])
X = invA @ b
print('X=', X)

X= [3. 2. 1.]


## Exercice 2

In [6]:
P = np.array([[1,1,1],
              [1,2,3],
              [1,4,8]])

__1)__ $A$ vaut :

In [7]:
A = np.array([[0,1,0],
              [0,0,1],
              [4,-8,5]])

__3)__ Méthode de résolution : tenter d'inverser $P$ en appliquant le pivot de Gauss, normalement tout se passe bien et on trouve :

In [8]:
np.linalg.inv(P)

array([[ 4., -4.,  1.],
       [-5.,  7., -2.],
       [ 2., -3.,  1.]])

__4)__

In [9]:
T = np.round(np.linalg.inv(P) @A @ P,2)
T

array([[ 1.,  0.,  0.],
       [-0.,  2.,  1.],
       [ 0.,  0.,  2.]])

In [10]:
D = np.diag([1,2,2])
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

In [11]:
J = np.zeros((3,3))
J[1,2] = 1
J 

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

__4')__

In [12]:
np.linalg.matrix_power(J,2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

$J^2=0$ donc $J^n = 0 \;\;\forall n \geq 2$ .

__4'')__

In [13]:
D@J - J@D

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Le produit $J\times D$ est commutatif : on peut donc appliquer la formule du binôme de Newton pour calculer $(J+D)^n$.

__5)__ Vérification de la formule trouvée avec $n=4$ :

In [14]:
np.linalg.matrix_power(T,4)

array([[ 1.,  0.,  0.],
       [ 0., 16., 32.],
       [ 0.,  0., 16.]])

__8)__ On trouve à la main :

In [15]:
def u_direct(n):
    return (2**n*(n-5) +2**(n+1)+4)*3 +(7*2**n-3*2**(n-1)*(n+2)-4) * 1 \
        + (1+n*2**(n-1)-2**(n+1)+2**n)*(-1)

__Vérification des résultats :__

In [16]:
u_direct(25)

704643079

In [17]:
X0 = np.array([3,1,-1])
np.linalg.matrix_power(A,25) @X0

array([  704643079,  1476395015, -1207959545])

__c'est bon__

## Chaînes de Markov.. à suivre