## EX 1 PARTIE A

In [23]:
A = np.array([[1, 0, -1,], [1,2,1], [2,2,3]])
A2 = A @ A
A3 = A2 @ A
A2, A3

(array([[-1, -2, -4],
        [ 5,  6,  4],
        [10, 10,  9]]),
 array([[-11, -12, -13],
        [ 19,  20,  13],
        [ 38,  38,  27]]))

In [24]:
a = 6
b = -11
c = 6

A3 - a * A2 -b * A - c* np.eye(3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
B = np.array([2, 8 , 13])
np.linalg.solve(A, B)

array([3., 2., 1.])

## EX 1 PARTIE B

In [26]:
P = np.array([[1, 2 ,1], [-1, -1, -1], [0, -2, -2]])

np.linalg.det(P), np.linalg.inv(P)

(-2.0,
 array([[ 0. , -1. ,  0.5],
        [ 1. ,  1. , -0. ],
        [-1. , -1. , -0.5]]))